#################################################################################################################
#
# IMPORTANT: This docker configuration must be use only for local execution and test purposes. PLEASE NOT APPLY THIS
# DOCKER DEPLOYMENT IN ANY CLOUD SERVER.
#
#################################################################################################################


version: '3.0'

services:
##################################################################################################################
############################################ Database container ##################################################
  db:
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    container_name: ppk-mysql
    volumes:
# If you have some data and structure already built, then you can add to mysql data volume, if not then keep this
# configuration.
    - db_data:/var/lib/mysql
    restart: always
# Update DB environment variables with your own values
    env_file:
      - payments.env
    ports:
    - "3307:3306"

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#    - "9090:8080"

#################################################################################################################
########################################### Application container ################################################
  ppk-payment-api:
    image: tomcat:8
# Update container name with your own project proper container name (project-service-type)
    container_name: ppk-payment-api
# Update this volume link with your own .war generated file
    volumes:
      - ${PWD}/target/pappking.be.api.war:/usr/local/tomcat/webapps/api.war
# You should create your own env variables to setup your app
    env_file:
      - payments.env
    restart: always
# Database must be linked to the project to be sure that they are in the same docker network
    links:
      - db
    depends_on:
      - db
# You must be sure that each application is dispatched by a different port to avoid service crash
    ports:
      - 8091:8080
volumes:
  db_data: